In [17]:
import torch
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(f'Using device: {device}')

Using device: cpu


In [5]:
randint = torch.randint(-100, 100, (6,))
print(randint)

tensor([ 88,  92,  -7,  65,  88, -46])


In [6]:
tensor = torch.tensor([[0.1, 1.2], [2.2, 3.1], [4.9, 5.2]])
print(tensor)

tensor([[0.1000, 1.2000],
        [2.2000, 3.1000],
        [4.9000, 5.2000]])


In [7]:
zeros = torch.zeros((2, 3))
print(zeros)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [8]:
ones = torch.ones((3, 4))
print(ones)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [11]:
input_ = torch.empty((2, 3))
print(input_)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [12]:
arrange = torch.arange(5)
print(arrange)

tensor([0, 1, 2, 3, 4])


In [13]:
linspacec = torch.linspace(3, 15, steps=5)
print(linspacec)

tensor([ 3.,  6.,  9., 12., 15.])


In [14]:
logspacec = torch.logspace(3, 15, steps=5)
print(logspacec)

tensor([1.0000e+03, 1.0000e+06, 1.0000e+09, 1.0000e+12, 1.0000e+15])


In [15]:
eye = torch.eye(4)
print(eye)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])


In [16]:
tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])
empty_like = torch.empty_like(tensor)
print(empty_like)

tensor([[2206237526192,             0,             0],
        [            0,             0,             0]])
